name: 'Matterfy'
description: 'Mattermost Notification for Github Actions'
author: 'tferreira'
inputs:
  type:
    description: 'job status (success or failure)'
    required: true
  msg:
    description: 'Custom message to send to MM'
    required: true
  show_ref:
    description: 'Custom message to send to MM'
    required: false
    default: 'false'
  username:
    description: 'mattermost username'
    required: false
    default: 'Github Actions'
  icon_emoji:
    description: 'mattermost icon emoji'
    required: false
    default: 'github'
  channels:
    description: 'mattermost channels (JSON string[])'
    required: true
  url:
    description: 'mattermost incoming webhook url'
    required: false
runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  icon: 'bell'
  color: 'green'